
logging:
  file: e:\mylog\log.log
  level: debug
#aicfe:
#  security:
#    browser:
#      loginPage: /demo-login.html
#      loginType: REDIRECT
spring:
  datasource:
    url: jdbc:mysql://localhost/test?autoReconnect=true&amp;zeroDateTimeBehavior=convertToNull&amp;useUnicode=true&amp;characterEncoding=UTF-8
    username: root
    password: root
  thymeleaf: 
    cache: false

aicfe:
  security:
    code:
      image:
        length: 6
        width: 100
        url: /findUserRole/*
    